server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.1.253:3306/linayi?serverTimezone=GMT
    username: dev_ess
    password: dev_ess
mybatis:
  mapper-locations: classpath:com/wei/mybatis/mapper/*.xml
  type-aliases-package: classpath:com.wei.mybatis.bo